### ISSUE TITLE
Starting replication process with Procfile

### ISSUE THREAD

**Issue by dhmacs** [fractaledmind/litestream-ruby#42]
The README of the project says that the replication process can be started with a procfile:

```procfile
# Procfile
rails: bundle exec rails server --port $PORT
litestream: bin/rails litestream:replicate
```

It seems though that if `bin/rails litestream:replicate` executes asynchronously, foreman (or whatever process monitor) would exit, stopping the other processes as well, correct?
I'm asking this because this is what's happening when I try this setup (when I run the puma plugin it works).

This seems to affect other commands like `restore` as well, which makes it hard to implement sequential logic (e.g. restoring the db before running  `bin/rails db:prepare` — useful when migrating to a new server for distaster recovery)

**Comment by olinelson** [comment]
Interesting. I can successfully run litestream with the puma plugin in Rails 8 but running as a separate process just exits. An excerpt from my Kamal config.
```yaml
servers:
  web:
    - 170.64.240.47
  worker:
    hosts:
        - 170.64.240.47
    cmd: bin/jobs
  litestream:
    hosts:
      - 170.64.240.47
    cmd: bin/rails litestream:replicate

```
