### ISSUE TITLE
Feature request: Make retention configurable

### ISSUE THREAD

**Issue by erdostom** [fractaledmind/litestream-ruby#53]
Some users may want longer retention than 24h.

Suggesting two new config items:
- retention
- snapshot_interval

**Comment by fractaledmind** [comment]
How do those map to configuration on the underlying Litestream utility?

**Comment by alxvernier** [comment]
I have set this config in my config/litestream.yml file for 3 days retention with full snapshot every 12 hours.

```yaml
dbs:
  - path: storage/${RAILS_ENV}.sqlite3
    replicas:
      - type: s3
        region: $LITESTREAM_REPLICA_REGION
        endpoint: $LITESTREAM_REPLICA_ENDPOINT
        bucket: $LITESTREAM_REPLICA_BUCKET
        path: app/storage/${RAILS_ENV}.sqlite3
        access-key-id: $LITESTREAM_ACCESS_KEY_ID
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
        retention: 72h
        snapshot-interval: 12h
```
